/*
* THIS MODULE IS THE "CLIENT" MODULE, AND IT CONTAINS THIS PACKAGE:
* com.entertainment.client
*
* AS THE "CLIENT", NO EXPORTING
*
 */

module com.entertainment.client {
//WHAT OTHER "MODULES" DOES THIS MODULE DEPEND ON? BUSINESS MODULE
// THIS MODULE WILL GET ACCES TO THE PUBLIC CLASSES IN EXPORTED PACKAGES

    requires com.entertainment; //T THIS IS A *MODULE*
}